#!/usr/local/bin/node

let fs = require("fs");
let Phrase = require("juliahop-palindrome");

let text = fs.readFileSync("phrases.txt", "utf-8");
text.split("\n").forEach(function(line) {
  let phrase = new Phrase(line);
  if (phrase.palindrome()) {
    fs.writeFile("palindromes.txt", phrase, (err) => {
      if (err) throw err;
    })
    console.log("palindrome detected:", line);
  }
});
